fs_jul19 Alex Andrutskii solution
mate-academy/js_deep-equal pull request #55
Opened 2019-08-14 12:57 UTC by aleks-and

2019-08-14 13:03 UTC, aleks-and commented
По-сути это не мое решение, пока разбирался как это сделать проще и эффективнее всего (не так просто как подключить библиотеку Lodash и использовать метод _.isEqual конечно))), нагуглилось решение.

2019-08-15 12:57 UTC, danheim commented
Ты понимаешь как оно работает?

2019-08-15 13:19 UTC, aleks-and commented
> Ты полностью понимаешь как оно работает?

Да, сидел разбирался в этом.

2019-08-15 13:52 UTC, danheim requested changes

2019-08-15 13:52 UTC, danheim commented on src/deepEqual.js
> +    aCountProps++;
`Object.keys(a).length`

2019-08-17 19:42 UTC, aleks-and commented on src/deepEqual.js
> +    aCountProps++;
Fixed!

2019-08-19 10:51 UTC, danheim approved these changes

2026-01-17 14:34 UTC, closed without merging